include: [html]

#Others
markdown: kramdown

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM 
    syntax_highlighter: rouge

# custom collection for grantgist
collections:
  grantgists:
    output: true               # so that Jekyll will output each item as a separate page
    permalink: /grantgists/:title/

